### ISSUE TITLE
add project image input to publish and edit pages

### ISSUE THREAD

**Issue by ntseng** [jdijaili/w20-teachables-group-project#141]
```
			projectImage: "" //TODO add project image input to publish and edit pages
```

https://github.com/jdijaili/w20-teachables-group-project/blob/954127a31965a69b5977329863b350a74b9f0726/react-app/src/components/PublishPage/PublishPage.js#L45

**Comment by kim-yura** [comment]
Link to pull request: https://github.com/jdijaili/w20-teachables-group-project/pull/145
