### ISSUE TITLE
Confirm category id numbers and seed data

### ISSUE THREAD

**Issue by ntseng** [jdijaili/w20-teachables-group-project#157]
Also test that changing categories via edit form works.

**Comment by kim-yura** [comment]
Category numbers are accurate as of latest main, but for @ntseng's category, do we want to call it Coding or Game Development? Currently our db data reflects "Coding" but the navbar reads "Game Development" (this is an easy fix).

**Comment by kim-yura** [comment]
Link to pull request: https://github.com/jdijaili/w20-teachables-group-project/pull/169
